export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const GET_POST_COUNT_SUCCESS = "GET_POST_COUNT_SUCCESS"
export const GET_VALIDATED_POST_SUCCESS = "GET_VALIDATED_POST_SUCCESS"
export const GET_INVALIDATED_POST_SUCCESS = "GET_INVALIDATED_POST_SUCCESS"
